[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons
admin_passwd = $pbkdf2-sha512$600000$o3QupdTaO8d4753z/t977w$CEcNBdLs4C.8JZ5UDsYDYqNgFjFudCln6ANzDw979BEHHEdVdVItEf00K2N0yOxrCtzkHOqijFQuC8nVWslEEA

